# Generated by Django 5.2 on 2025-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_recycleactivityitem_recycle_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclebag",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
