# Generated by Django 5.2 on 2025-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_branch_store_qrcodeusage_branch_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="email",
        ),
        migrations.AddField(
            model_name="branch",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    ("beheira", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north_sinai", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Qalyubia"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AddField(
            model_name="store",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hypermarkets", "Hypermarkets"),
                    ("cafes", "Cafes"),
                    ("restaurants", "Restaurants"),
                    ("dessert_shops", "Dessert shops"),
                    ("pharmacies", "Pharmacies"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
