# Generated by Django 5.2 on 2025-04-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_store_email_branch_governorate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="voucher_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    ("beheira", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north Thorpe", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Qalyubia"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recyclebag",
            name="status",
            field=models.CharField(
                choices=[(" WORKS", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="VoucherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.branch",
                    ),
                ),
            ],
        ),
    ]
