# Generated by Django 5.2 on 2025-04-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_recyclebag_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucherlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("USED", "Used"),
                    ("DELETED", "Deleted"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="voucherlog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.branch",
            ),
        ),
    ]
