# Generated by Django 5.2 on 2025-04-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    ("beheira", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north_sinai", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Bunkerry"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.register",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
