# Generated by Django 5.2 on 2025-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_branch_governorate_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherlog",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
