# Generated by Django 5.2 on 2025-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_voucherlog_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherlog",
            name="transaction_id",
        ),
    ]
