# Generated by Django 5.2 on 2025-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_voucherlog_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[("earn", "Earn"), ("redeem", "Redeem"), ("cancel", "Cancel")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recyclebag",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
