# Generated by Django 5.2 on 2025-05-08 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_activity_type_alter_recyclebag_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclebag",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="recyclebag",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.user_profile_pic_path
            ),
        ),
    ]
