# Generated by Django 5.2 on 2025-05-10 23:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_recyclebag_latitude_recyclebag_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=15)),
                ("birth_date", models.DateField()),
                ("phone_number", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.delivery_boy_profile_pic_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
