# Generated by Django 5.2 on 2025-05-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_deliveryboy_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryboy",
            name="country",
        ),
        migrations.RemoveField(
            model_name="deliveryboy",
            name="work_area",
        ),
        migrations.RemoveField(
            model_name="register",
            name="country",
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    ("beheira", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north_sinai", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Qalyubia"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("delivery_boy", "Delivery Boy")],
                default="delivery_boy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="register",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    ("beheira", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north_sinai", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Qalyubia"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryassignment",
            name="delivery_boy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.deliveryboy"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryassignment",
            name="recycle_bag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.recyclebag"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("delivery_boy", "Delivery Boy")],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hyper markets", "Hypermarkets"),
                    ("cafes", "Cafes"),
                    ("restaurants", "Restaurants"),
                    ("dessert_shops", "Dessert shops"),
                    ("pharmacies", "Pharmacies"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
