# Generated by Django 5.2 on 2025-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_deliveryboy_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclebag",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
