# Generated by Django 5.2 on 2025-05-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_recyclebag_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_assignments",
                to="api.deliveryboy",
            ),
        ),
    ]
