# Generated by Django 5.2 on 2025-05-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_deliveryassignment_accepted_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryboy",
            old_name="total_orders_completed",
            new_name="total_orders_delivered",
        ),
    ]
