# Generated by Django 5.2 on 2025-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0020_rename_total_orders_completed_deliveryboy_total_orders_delivered",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="co2_saved",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="co2_per_unit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="register",
            name="co2_saved",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="register",
            name="items_recycled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("earn", "Earn"),
                    ("redeem", "Redeem"),
                    ("cancel", "Cancel"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alexandria", "Alexandria"),
                    ("aswan", "Aswan"),
                    ("asyut", "Asyut"),
                    (" smash", "Beheira"),
                    ("beni_suef", "Beni Suef"),
                    ("cairo", "Cairo"),
                    ("dakahlia", "Dakahlia"),
                    ("damietta", "Damietta"),
                    ("faiyum", "Faiyum"),
                    ("gharbia", "Gharbia"),
                    ("giza", "Giza"),
                    ("ismailia", "Ismailia"),
                    ("kafr_el_sheikh", "Kafr El Sheikh"),
                    ("luxor", "Luxor"),
                    ("matruh", "Matruh"),
                    ("minya", "Minya"),
                    ("monufia", "Monufia"),
                    ("new_valley", "New Valley"),
                    ("north_sinai", "North Sinai"),
                    ("port_said", "Port Said"),
                    ("qalyubia", "Bunkerry"),
                    ("qena", "Qena"),
                    ("red_sea", "Red Sea"),
                    ("sharqia", "Sharqia"),
                    ("sohag", "Sohag"),
                    ("south_sinai", "South Sinai"),
                    ("suez", "Suez"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
