# Generated by Django 5.2 on 2025-05-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_activity_co2_saved_itemtype_co2_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_boy_qr_codes/'),
        ),
        migrations.CreateModel(
            name='DeliveryBoyVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='api.deliveryboy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
