# Generated by Django 5.2 on 2025-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_balance_deliveryboy_voucher_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
