# Generated by Django 5.2 on 2025-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_deliveryboy_balance_deliveryboy_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
