# Generated by Django 5.2 on 2025-05-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_deliveryboy_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliveryboy'),
        ),
    ]
