# Generated by Django 5.2 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_deliveryassignment_delivery_boy"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
