# Generated by Django 5.2 on 2025-05-14 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_register_address_alter_itemtype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryassignment",
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="chat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="delivery_boy_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="delivery_boy_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="last_status_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="user_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryassignment",
            name="user_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "User"), ("delivery_boy", "Delivery Boy")],
                        max_length=20,
                    ),
                ),
                ("sender_id", models.IntegerField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.deliveryassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
