# Generated by Django 5.2 on 2025-05-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_chatmessage_sender_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deliveryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "accepted", "in_transit"])
                ),
                fields=("recycle_bag",),
                name="unique_active_assignment",
            ),
        ),
    ]
