# Generated by Django 5.2 on 2025-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_deliveryassignment_unique_active_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryassignment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recyclebag",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recyclebag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recyclebag",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("accepted", "Accepted"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
