# Generated by Django 5.2 on 2025-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_deliveryboyreward'),
        ('api', '0031_deliveryassignment_rejection_reason_and_more'),
    ]

    operations = [
    ]
