# Generated by Django 5.2 on 2025-05-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20250515_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyvoucher',
            name='used_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vouchers', to='api.branch'),
        ),
    ]
