# Generated by Django 5.2 on 2025-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_deliveryboyvoucher_used_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyvoucher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_vouchers_qr/'),
        ),
    ]
