# Generated by Django 5.2 on 2025-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_deliveryboyvoucher_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='voucher_amount',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='voucher_expiry',
        ),
    ]
