# Generated by Django 5.2 on 2025-05-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_deliveryboy_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='balance',
        ),
    ]
