# Generated by Django 5.2 on 2025-05-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_deliveryboy_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='average_rating',
        ),
    ]
