# Generated by Django 5.2 on 2025-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_deliveryboy_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
