# Generated by Django 5.2 on 2025-05-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_deliveryboy_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboyrating',
            name='delivery_boy_comment',
        ),
        migrations.RemoveField(
            model_name='deliveryboyrating',
            name='delivery_boy_rating',
        ),
    ]
