# Generated by Django 5.2 on 2025-05-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_deliveryboyrating_delivery_boy_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeusage',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code_usages', to='api.deliveryboy'),
        ),
    ]
