# Generated by Django 5.2 on 2025-05-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_qrcodeusage_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='register',
            name='voucher_amount',
        ),
        migrations.RemoveField(
            model_name='register',
            name='voucher_expiry',
        ),
        migrations.CreateModel(
            name='CustomerVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='customer_vouchers_qr/')),
                ('used_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_used_vouchers', to='api.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='api.register')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VoucherLog',
        ),
    ]
