# Generated by Django 5.2 on 2025-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_remove_register_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryboy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
