# Generated by Django 5.2 on 2025-06-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_deliveryboy_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryboy",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
